#include "PluginEditor.h"
static const char* names[]={"KICK","SNARE","TOM","METAL HAT","FM PERC","PHASE PERC","WAVE METAL","NOISE RESO","SAMPLE 1","SAMPLE 2","SAMPLE 3","SYNTH"};
JerzyDrumMachineAudioProcessorEditor::JerzyDrumMachineAudioProcessorEditor(JerzyDrumMachineAudioProcessor&x):AudioProcessorEditor(&x),p(x){
 setSize(1280,720);setResizable(true,true);setResizeLimits(960,540,1920,1080);
 for(auto*b:{&seq,&sound,&mix,&generate,&mutate,&fill,&loadSample})addAndMakeVisible(*b);
 seq.onClick=[this]{page=0;resized();repaint();};sound.onClick=[this]{page=1;resized();repaint();};mix.onClick=[this]{page=2;resized();repaint();};
 for(int i=0;i<12;i++){instruments[i].setButtonText(names[i]);addAndMakeVisible(instruments[i]);instruments[i].onClick=[this,i]{selected=i;for(int pidx=0;pidx<4;pidx++)soundParam[pidx].setValue(p.engine.getVoiceParam(selected,pidx),juce::dontSendNotification);resized();repaint();};}
 for(int s=0;s<16;s++){steps[s].setButtonText(juce::String(s+1));addAndMakeVisible(steps[s]);steps[s].onClick=[this,s]{auto&st=p.engine.pattern(p.engine.getPattern()).step[selected][s];st.on=!st.on;steps[s].setToggleState(st.on,juce::dontSendNotification);};}
 generate.onClick=[this]{p.engine.generate(p.apvts.getRawParameterValue("density")->load(),p.apvts.getRawParameterValue("variation")->load());repaint();};
 mutate.onClick=[this]{p.engine.mutate(p.apvts.getRawParameterValue("variation")->load());repaint();};
 fill.onClick=[this]{p.engine.fill();repaint();};
 loadSample.onClick=[this]{if(selected<8||selected>10)return;chooser=std::make_unique<juce::FileChooser>("Load WAV sample",juce::File{},"*.wav;*.aif;*.aiff");auto flags=juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles;chooser->launchAsync(flags,[this](const juce::FileChooser&fc){auto file=fc.getResult();if(file.existsAsFile())p.engine.loadSample(selected-8,file);repaint();});};
 for(int i=0;i<12;i++){for(auto*s:{&channelGain[i],&channelPan[i],&revSend[i],&delSend[i]}){addAndMakeVisible(*s);s->setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);s->setTextBoxStyle(juce::Slider::NoTextBox,false,0,0);}channelGain[i].setRange(0,1.5,.01);channelGain[i].setValue(p.engine.gain[i]);channelGain[i].onValueChange=[this,i]{p.engine.gain[i]=(float)channelGain[i].getValue();};channelPan[i].setRange(-1,1,.01);channelPan[i].onValueChange=[this,i]{p.engine.panorama[i]=(float)channelPan[i].getValue();};revSend[i].setRange(0,1,.01);revSend[i].setValue(p.engine.reverbSend[i]);revSend[i].onValueChange=[this,i]{p.engine.reverbSend[i]=(float)revSend[i].getValue();};delSend[i].setRange(0,1,.01);delSend[i].setValue(p.engine.delaySend[i]);delSend[i].onValueChange=[this,i]{p.engine.delaySend[i]=(float)delSend[i].getValue();};}addAndMakeVisible(masterDrive);masterDrive.setRange(.5,3,.01);masterDrive.setValue(p.engine.drive);masterDrive.onValueChange=[this]{p.engine.drive=(float)masterDrive.getValue();};
 startTimerHz(20);
}
void JerzyDrumMachineAudioProcessorEditor::paint(juce::Graphics&g){
 g.fillAll(juce::Colour(0xff090807)); auto r=getLocalBounds().toFloat();g.setColour(juce::Colour(0xff4b2b1d));g.drawRoundedRectangle(r.reduced(6),8,2);
 g.setColour(juce::Colour(0xffc47a38));g.setFont(26);g.drawText("JERZY  DRUM MACHINE",22,12,340,36,juce::Justification::centredLeft);
 g.setFont(14);g.setColour(juce::Colour(0xffd6a45e));g.drawText(page==0?"SEQ / PATTERN":page==1?"SOUND / INSTRUMENT":"MIX / FX",22,82,300,28,juce::Justification::left);
 if(page==1){g.setFont(32);g.drawText(names[selected],420,150,500,50,juce::Justification::centred);g.setFont(16);g.drawText(selected<4?"ANALOG MODEL":selected<8?"DIGITAL SYNTHESIS":selected<11?"SAMPLE ENGINE":"SYNTH VOICE",420,205,500,30,juce::Justification::centred);static const char*spn[]={"TUNE","DECAY","TONE","CHARACTER"};for(int i=0;i<4;i++)g.drawText(spn[i],350+i*150,315,120,24,juce::Justification::centred);if(selected>=8&&selected<=10)g.drawText(p.engine.getSampleName(selected-8).isEmpty()?"NO SAMPLE LOADED":p.engine.getSampleName(selected-8),420,255,500,30,juce::Justification::centred);}
 if(page==2){g.setFont(20);g.drawText("12 CHANNEL MIXER   |   LEVEL / PAN / REVERB / DELAY",190,92,900,35,juce::Justification::centred);g.setFont(12);for(int i=0;i<12;i++)g.drawText(names[i],30+i*((getWidth()-60)/12),145,(getWidth()-70)/12,22,juce::Justification::centred);g.drawText("MASTER DRIVE",getWidth()-180,590,140,24,juce::Justification::centred);}
}
void JerzyDrumMachineAudioProcessorEditor::resized(){
 auto w=getWidth();seq.setBounds(390,18,100,40);sound.setBounds(496,18,100,40);mix.setBounds(602,18,100,40);
 bool isSeq=page==0;for(int i=0;i<12;i++){instruments[i].setVisible(isSeq);instruments[i].setBounds(24,120+i*38,150,30);}
 for(int s=0;s<16;s++){steps[s].setVisible(isSeq);steps[s].setBounds(190+s*((w-230)/16),140,(w-250)/16,300);}
 generate.setVisible(isSeq);mutate.setVisible(isSeq);fill.setVisible(isSeq);loadSample.setVisible(page==1&&selected>=8&&selected<=10);loadSample.setBounds(w/2-70,330,140,38);bool isSound=page==1;for(int i=0;i<4;i++){soundParam[i].setVisible(isSound);soundParam[i].setBounds(350+i*150,350,120,110);}bool isMix=page==2;int cw=(w-60)/12;for(int i=0;i<12;i++){int x=30+i*cw;channelGain[i].setVisible(isMix);channelPan[i].setVisible(isMix);revSend[i].setVisible(isMix);delSend[i].setVisible(isMix);channelGain[i].setBounds(x,180,cw-4,80);channelPan[i].setBounds(x,270,cw-4,70);revSend[i].setBounds(x,350,cw-4,70);delSend[i].setBounds(x,430,cw-4,70);}masterDrive.setVisible(isMix);masterDrive.setBounds(w-180,615,140,70);generate.setBounds(w-360,610,110,38);mutate.setBounds(w-240,610,100,38);fill.setBounds(w-130,610,90,38);
}
