#include "PluginEditor.h"
static const char* names[]={"KICK","SNARE","TOM","METAL HAT","FM PERC","PHASE PERC","WAVE METAL","NOISE RESO","SAMPLE 1","SAMPLE 2","SAMPLE 3","SYNTH"};
JerzyDrumMachineAudioProcessorEditor::JerzyDrumMachineAudioProcessorEditor(JerzyDrumMachineAudioProcessor&x):AudioProcessorEditor(&x),p(x){
 setSize(1280,720);setResizable(true,true);setResizeLimits(960,540,1920,1080);
 for(auto*b:{&seq,&sound,&mix,&generate,&mutate,&fill,&loadSample,&saveKit,&loadKit})addAndMakeVisible(*b);
 seq.onClick=[this]{page=0;resized();repaint();};sound.onClick=[this]{page=1;resized();repaint();};mix.onClick=[this]{page=2;resized();repaint();};
 for(int i=0;i<12;i++){instruments[i].setButtonText(names[i]);addAndMakeVisible(instruments[i]);instruments[i].onClick=[this,i]{selected=i;for(int pidx=0;pidx<4;pidx++)soundParam[pidx].setValue(p.engine.getVoiceParam(selected,pidx),juce::dontSendNotification);resized();repaint();};}
 for(int b=0;b<4;b++){banks[b].setButtonText("BANK "+juce::String(b+1));addAndMakeVisible(banks[b]);banks[b].onClick=[this,b]{bank=b;for(int s=0;s<16;s++){auto&st=p.engine.pattern(p.engine.getPattern()).step[selected][bank*16+s];steps[s].setToggleState(st.on,juce::dontSendNotification);}repaint();};}
 for(int s=0;s<16;s++){steps[s].setButtonText(juce::String(s+1));addAndMakeVisible(steps[s]);steps[s].onClick=[this,s]{selectedStep=bank*16+s;auto&st=p.engine.pattern(p.engine.getPattern()).step[selected][selectedStep];st.on=!st.on;steps[s].setToggleState(st.on,juce::dontSendNotification);stepVelocity.setValue(st.velocity,juce::dontSendNotification);stepProbability.setValue(st.probability,juce::dontSendNotification);stepRatchet.setValue(st.ratchet,juce::dontSendNotification);stepAccent.setToggleState(st.accent,juce::dontSendNotification);stepFlam.setToggleState(st.flam,juce::dontSendNotification);stepMicro.setValue(st.micro,juce::dontSendNotification);};}
 for(int i=0;i<8;i++){addAndMakeVisible(genParam[i]);genParam[i].setRange(0,1,.01);genParam[i].setValue(i==4?.85:(i==5?.9:(i==6?.65:(i==7?.35:.25))));genParam[i].setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);genParam[i].setTextBoxStyle(juce::Slider::NoTextBox,false,0,0);}
 auto updateGen=[this]{p.engine.setGenerator((float)genParam[0].getValue(),(float)genParam[1].getValue(),(float)genParam[2].getValue(),(float)genParam[3].getValue(),(float)genParam[4].getValue(),(float)genParam[5].getValue(),(float)genParam[6].getValue(),(float)genParam[7].getValue());};for(auto&s:genParam)s.onValueChange=updateGen;updateGen();
 generate.onClick=[this]{p.engine.generate(p.apvts.getRawParameterValue("density")->load(),p.apvts.getRawParameterValue("variation")->load());repaint();};
 mutate.onClick=[this]{p.engine.mutate(p.apvts.getRawParameterValue("variation")->load());repaint();};
 fill.onClick=[this]{p.engine.fill();repaint();};
 loadSample.onClick=[this]{if(selected<8||selected>10)return;chooser=std::make_unique<juce::FileChooser>("Load WAV sample",juce::File{},"*.wav;*.aif;*.aiff");auto flags=juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles;chooser->launchAsync(flags,[this](const juce::FileChooser&fc){auto file=fc.getResult();if(file.existsAsFile())p.engine.loadSample(selected-8,file);repaint();});};
 for(int i=0;i<12;i++){for(auto*s:{&channelGain[i],&channelPan[i],&revSend[i],&delSend[i]}){addAndMakeVisible(*s);s->setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);s->setTextBoxStyle(juce::Slider::NoTextBox,false,0,0);}channelGain[i].setRange(0,1.5,.01);channelGain[i].setValue(p.engine.gain[i]);channelGain[i].onValueChange=[this,i]{p.engine.gain[i]=(float)channelGain[i].getValue();};channelPan[i].setRange(-1,1,.01);channelPan[i].onValueChange=[this,i]{p.engine.panorama[i]=(float)channelPan[i].getValue();};revSend[i].setRange(0,1,.01);revSend[i].setValue(p.engine.reverbSend[i]);revSend[i].onValueChange=[this,i]{p.engine.reverbSend[i]=(float)revSend[i].getValue();};delSend[i].setRange(0,1,.01);delSend[i].setValue(p.engine.delaySend[i]);delSend[i].onValueChange=[this,i]{p.engine.delaySend[i]=(float)delSend[i].getValue();};}addAndMakeVisible(masterDrive);masterDrive.setRange(.5,3,.01);masterDrive.setValue(p.engine.drive);masterDrive.onValueChange=[this]{p.engine.drive=(float)masterDrive.getValue();};
 for(auto*s:{&stepVelocity,&stepProbability,&stepRatchet}){addAndMakeVisible(*s);s->setSliderStyle(juce::Slider::LinearHorizontal);s->setTextBoxStyle(juce::Slider::TextBoxRight,false,56,20);}addAndMakeVisible(stepAccent);addAndMakeVisible(stepFlam);addAndMakeVisible(patternLength);addAndMakeVisible(patternSelect);addAndMakeVisible(stepMicro);addAndMakeVisible(changeMode);
 stepVelocity.setRange(0.0,1.0,.01);stepProbability.setRange(0.0,1.0,.01);stepRatchet.setRange(1,4,1);patternLength.setRange(1,64,1);stepMicro.setRange(0.0,1.0,.01);stepMicro.setSliderStyle(juce::Slider::LinearHorizontal);stepMicro.setTextBoxStyle(juce::Slider::TextBoxRight,false,56,20);changeMode.addItem("IMMEDIATE",1);changeMode.addItem("NEXT BEAT",2);changeMode.addItem("NEXT BAR",3);changeMode.addItem("END PATTERN",4);changeMode.setSelectedId(4);patternLength.setValue(p.engine.pattern(p.engine.getPattern()).length);for(int i=0;i<32;i++)patternSelect.addItem("PATTERN "+juce::String(i+1)+" / "+juce::MidiMessage::getMidiNoteName(60+i,true,true,3),i+1);patternSelect.setSelectedId(p.engine.getPattern()+1);
 stepVelocity.onValueChange=[this]{p.engine.pattern(p.engine.getPattern()).step[selected][selectedStep].velocity=(float)stepVelocity.getValue();};
 stepProbability.onValueChange=[this]{p.engine.pattern(p.engine.getPattern()).step[selected][selectedStep].probability=(float)stepProbability.getValue();};
 stepRatchet.onValueChange=[this]{p.engine.pattern(p.engine.getPattern()).step[selected][selectedStep].ratchet=(int)stepRatchet.getValue();};
 stepAccent.onClick=[this]{p.engine.pattern(p.engine.getPattern()).step[selected][selectedStep].accent=stepAccent.getToggleState();};
 stepFlam.onClick=[this]{p.engine.pattern(p.engine.getPattern()).step[selected][selectedStep].flam=stepFlam.getToggleState();};stepMicro.onValueChange=[this]{p.engine.pattern(p.engine.getPattern()).step[selected][selectedStep].micro=(float)stepMicro.getValue();};changeMode.onChange=[this]{p.engine.setChangeMode((DrumEngine::ChangeMode)(changeMode.getSelectedId()-1));};
 patternLength.onValueChange=[this]{p.engine.pattern(p.engine.getPattern()).length=(int)patternLength.getValue();};
 patternSelect.onChange=[this]{p.engine.setPattern(patternSelect.getSelectedId()-1);patternLength.setValue(p.engine.pattern(p.engine.getPattern()).length,juce::dontSendNotification);repaint();};
 saveKit.onClick=[this]{kitChooser=std::make_unique<juce::FileChooser>("Save Jerzy Drum Kit",juce::File{},"*.jdmkit");kitChooser->launchAsync(juce::FileBrowserComponent::saveMode|juce::FileBrowserComponent::canSelectFiles,[this](const juce::FileChooser&fc){auto file=fc.getResult();if(file.getFileExtension().isEmpty())file=file.withFileExtension(".jdmkit");if(auto xml=p.engine.saveState().createXml())xml->writeTo(file);});};
 loadKit.onClick=[this]{kitChooser=std::make_unique<juce::FileChooser>("Load Jerzy Drum Kit",juce::File{},"*.jdmkit");kitChooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this](const juce::FileChooser&fc){auto file=fc.getResult();if(auto xml=juce::XmlDocument::parse(file)){p.engine.loadState(juce::ValueTree::fromXml(*xml));repaint();}});};
 startTimerHz(20);
}
void JerzyDrumMachineAudioProcessorEditor::paint(juce::Graphics&g){
 g.fillAll(juce::Colour(0xff090807)); auto r=getLocalBounds().toFloat();g.setColour(juce::Colour(0xff4b2b1d));g.drawRoundedRectangle(r.reduced(6),8,2);
 g.setColour(juce::Colour(0xffc47a38));g.setFont(26);g.drawText("JERZY  DRUM MACHINE",22,12,340,36,juce::Justification::centredLeft);
 g.setFont(14);g.setColour(juce::Colour(0xffd6a45e));g.drawText(page==0?"SEQ / PATTERN":page==1?"SOUND / INSTRUMENT":"MIX / FX",22,82,300,28,juce::Justification::left);
 if(page==1){g.setFont(32);g.drawText(names[selected],420,150,500,50,juce::Justification::centred);g.setFont(16);g.drawText(selected<4?"ANALOG MODEL":selected<8?"DIGITAL SYNTHESIS":selected<11?"SAMPLE ENGINE":"SYNTH VOICE",420,205,500,30,juce::Justification::centred);static const char*spn[]={"TUNE","DECAY","TONE","CHARACTER"};for(int i=0;i<4;i++)g.drawText(spn[i],350+i*150,315,120,24,juce::Justification::centred);if(selected>=8&&selected<=10)g.drawText(p.engine.getSampleName(selected-8).isEmpty()?"NO SAMPLE LOADED":p.engine.getSampleName(selected-8),420,255,500,30,juce::Justification::centred);}
 if(page==0){g.setFont(13);g.drawText("VELOCITY",220,510,90,22,juce::Justification::left);static const char*gn[]={"COMPLEX","SYNCOP","HUMAN","CHAOS","KICK STAB","SNARE STAB","HAT ACT","PERC ACT"};for(int i=0;i<8;i++)g.drawText(gn[i],40+i*115,650,100,20,juce::Justification::centred);g.drawText("PROBABILITY",220,545,100,22,juce::Justification::left);g.drawText("RATCHET",220,580,90,22,juce::Justification::left);g.drawText("PATTERN LENGTH",700,510,120,22,juce::Justification::left);g.drawText("PATTERN / MIDI NOTE",680,545,140,22,juce::Justification::left);g.drawText("MICROTIMING",220,615,90,22,juce::Justification::left);g.drawText("CHANGE MODE",700,580,110,22,juce::Justification::left);} if(page==2){g.setFont(20);g.drawText("12 CHANNEL MIXER   |   LEVEL / PAN / REVERB / DELAY",190,92,900,35,juce::Justification::centred);g.setFont(12);for(int i=0;i<12;i++)g.drawText(names[i],30+i*((getWidth()-60)/12),145,(getWidth()-70)/12,22,juce::Justification::centred);g.drawText("MASTER DRIVE",getWidth()-180,590,140,24,juce::Justification::centred);}
}
void JerzyDrumMachineAudioProcessorEditor::resized(){
 auto w=getWidth();seq.setBounds(390,18,100,40);sound.setBounds(496,18,100,40);mix.setBounds(602,18,100,40);
 bool isSeq=page==0;for(int i=0;i<12;i++){instruments[i].setVisible(isSeq);instruments[i].setBounds(24,120+i*38,150,30);}
 for(int b=0;b<4;b++){banks[b].setVisible(isSeq);banks[b].setBounds(190+b*105,100,95,30);}
 for(int s=0;s<16;s++){steps[s].setVisible(isSeq);steps[s].setBounds(190+s*((w-230)/16),140,(w-250)/16,300);}
 stepVelocity.setVisible(isSeq);stepProbability.setVisible(isSeq);stepRatchet.setVisible(isSeq);stepAccent.setVisible(isSeq);stepFlam.setVisible(isSeq);patternLength.setVisible(isSeq);patternSelect.setVisible(isSeq);stepMicro.setVisible(isSeq);changeMode.setVisible(isSeq);
 stepVelocity.setBounds(320,505,260,28);stepProbability.setBounds(320,540,260,28);stepRatchet.setBounds(320,575,260,28);stepAccent.setBounds(600,575,100,28);stepFlam.setBounds(705,575,90,28);patternLength.setBounds(820,505,180,28);patternSelect.setBounds(820,540,220,28);stepMicro.setBounds(320,610,260,28);changeMode.setBounds(820,575,220,28);
 generate.setVisible(isSeq);mutate.setVisible(isSeq);fill.setVisible(isSeq);for(int i=0;i<8;i++){genParam[i].setVisible(isSeq);genParam[i].setBounds(45+i*115,675,90,65);}loadSample.setVisible(page==1&&selected>=8&&selected<=10);loadSample.setBounds(w/2-70,330,140,38);saveKit.setVisible(page==1);loadKit.setVisible(page==1);saveKit.setBounds(30,620,110,34);loadKit.setBounds(150,620,110,34);bool isSound=page==1;for(int i=0;i<4;i++){soundParam[i].setVisible(isSound);soundParam[i].setBounds(350+i*150,350,120,110);}bool isMix=page==2;int cw=(w-60)/12;for(int i=0;i<12;i++){int x=30+i*cw;channelGain[i].setVisible(isMix);channelPan[i].setVisible(isMix);revSend[i].setVisible(isMix);delSend[i].setVisible(isMix);channelGain[i].setBounds(x,180,cw-4,80);channelPan[i].setBounds(x,270,cw-4,70);revSend[i].setBounds(x,350,cw-4,70);delSend[i].setBounds(x,430,cw-4,70);}masterDrive.setVisible(isMix);masterDrive.setBounds(w-180,615,140,70);generate.setBounds(w-360,610,110,38);mutate.setBounds(w-240,610,100,38);fill.setBounds(w-130,610,90,38);
}
